#ifndef TEMPHUMSHT20PARCELHANDLER_H
#define TEMPHUMSHT20PARCELHANDLER_H

#include "ProtocolParser/BaseParcelHandler.h"

/**
 * @file    TempHumSHT20ParcelHandler.h
 * @date    2018-06-21
 * @author  sauber
 * @brief   The TempHumSHT20ParcelHandler class header file. This class will handle received built parcels for sensor
 * DSDTech SHT20.
 */


class TempHumSHT20ParcelHandler : public BaseParcelHandler
{
public:
    TempHumSHT20ParcelHandler();
    /**
     * @brief The EventType enum - all possible events which could be generated by parcel handling
     */
    enum EventType
    {
        TEMPERATURE_VALUE_UPDATED,
        HUMIDITY_VALUE_UPDATED,
        PARCEL_NOT_RECOGNIZED
    };
    /**
     * @brief getTempValue - returns the last read temerature value
     * @return - current temperature value
     */
    float getTempValue();
    /**
     * @brief getHumidityValue - returns the last read humidity value
     * @return - current humidity value
     */
    float getHumidityValue();
private:
    float mTemperatureValue = 0;
    float mHumidityValue = 0;
protected:
protected:
    /**
     * @brief handleParcel - this method handles received parcel and if this parcel was recognized, stores the received info and emits signal
     * @param parcel - received parcel to handle
     */
    virtual void handleParcel(Parcel& parcel);
};

#endif // TEMPHUMSHT20PARCELHANDLER_H
